#!/usr/bin/php
<?php
$flags = @count(['h' => $help, 'pure' => $pure, 'no-laravel' => $no_laravel, 'test' => $is_test, 'name' => $name] = getopt('h', ['pure','no-laravel','test','name:']));
['packages' => $packages, 'dist' => $dist] = json_decode(file_get_contents('scratch.json'), 1);
$pad_right = max(array_map('strlen', array_column($packages, 'name')));

if (!$flags || !is_null($help)) {
    echo "\33[1;37m
    Laravel 5 scratch installer v1.0

    \33[1;32mOptions:\33[1;37m
           -h              Show this help message
           --name=project  \33[1;33mRequired\33[1;37m Name of new project
        
           --pure          Do not install additional packages
           --no-laravel    Do not create project, just add packages

    \33[1;32mPackages to be installed:\33[1;37m\n";
    foreach ($packages as $package) {
        $name = str_pad($package['name'], $pad_right+2, ' ', STR_PAD_RIGHT);
        echo ($package['ignore'] ?? false) ? "\33[0;37m [ignored] \33[1;30m" : "           ";
        echo "{$name} {$package['description']}\33[1;37m\n";
    }
    echo "\033[0m\n";return;
}

if (is_null($name)) {
    echo "\33[1;33mNo project name specified!\033[0m\n";return;
}

function status($pid)
{
    exec("ps -p $pid", $state);
    return $state[1] ?? false;
}

function show_progress($index = 0)
{
    return  ['[=...]','[.=..]','[..=.]','[...=]','[..=.]','[.=..]'][$index];
}

function run_command($command)
{
    $state = 0;
    exec("{$command} >> /dev/null 2>&1 & echo $!", $pid);
    echo show_progress();
    while (status($pid[0])) {
        echo "\033[6D" . show_progress($state++ % 6);
    }
    echo "\033[6D\33[1;32mDone ✓\33[1;37m\n";
}

function execute($command, $is_test=false)
{
    $is_test ?run_command(''): run_command($command);
}

function install($package, $pad_right, $name, $is_test, $is_laravel = false)
{
    echo "Install " . str_pad($package['name'] . ':', $pad_right+2, ' ', STR_PAD_RIGHT);
    if ($is_laravel) {
        execute("composer {$package['composer']} {$name}", $is_test);
    } else {
        execute("cd {$name} && composer require {$package['composer']}", $is_test);
    }
    if (array_key_exists('commands', $package)) {
        foreach ($package['commands'] as $index => $config) {
            $i = $index +1;
            $all = count($package['commands']);
            echo str_pad(" + config ({$i}/{$all}):", $pad_right+10, ' ', STR_PAD_RIGHT);
            
            execute("cd {$name} && {$config}", $is_test);
        }
    }
}

$time = microtime(1);
$is_test = !is_null($is_test);

echo "\33[1;32mCreating new Laravel 5 project '{$name}'...\33[1;37m\n\n";
(is_null($no_laravel)) && install($dist, $pad_right, $name, $is_test, true);
(is_null($pure) && count($packages)) && array_walk($packages, function($package) use ($pad_right, $name, $is_test){
    if ($package['ignore'] ?? false) return;
    install($package, $pad_right, $name, $is_test);
});

$time -= microtime(1);
$timestamp = sprintf('%02d:%02d', -$time/60, -$time%60);

echo "\n\33[1;32mLaravel 5 project '{$name}' successfully created\33[1;37m in {$timestamp} min \033[0m\n";
